version: '3.3'

services:
  reminder:
    build: .
    container_name: tg-mentoring-otp-bot
    ports:
      - "172.17.0.1:8010:8010" # host.docker.internal
      - "127.0.0.1:8010:8010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - deploy/config.env
      - ~/common-config/config.env
