
server:
  port: 8011

spring:
  kafka:
    bootstrap-servers:
      - host.docker.internal:29092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: tg-mentoring-otp-bot
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

bot:
  name: ${TG_BOT_NAME}
  token: ${TG_BOT_TOKEN}
  kafka:
    send-otp:
      enabled: true
      topic-in: Send.Otp.IN.V1
      topic-out: Send.Otp.OUT.V1